apiVersion: v1
kind: Pod
metadata:
name: hadoop-datanode-1
labels:
  app: hadoop-datanode-1
spec:
containers:
- name: hadoop-datanode-1
  image: kubeguide/hadoop
  imagePullPolicy: IfNotPresent
  ports:
    - containerPort: 9000
    - containerPort: 50070    
  env:
    - name: HADOOP_NODE_TYPE
      value: datanode
    - name: HDFS_MASTER_SERVICE
      valueFrom:
        configMapKeyRef:
          name: ku8-hadoop-conf
          key: HDFS_MASTER_SERVICE
    - name: HDOOP_YARN_MASTER
      valueFrom:
        configMapKeyRef:
          name: ku8-hadoop-conf
          key: HDOOP_YARN_MASTER        
restartPolicy: Always
